// examples/getting-started/angular/src/app/app.component.ts
import { Component, ElementRef, ViewChild, OnDestroy, NgZone } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SuperDoc } from 'superdoc';
import { HocuspocusProvider } from '@hocuspocus/provider';
import * as Y from 'yjs';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="app">
      <header class="header">
        <div class="header-actions">
          <button class="btn outlined" (click)="fileInput.click()">
            Import
          </button>
          <input
            #fileInput
            type="file"
            accept=".docx"
            (change)="onFileChange($event)"
            hidden
          />
          <button
            class="btn filled"
            (click)="exportDocument()"
          >
            Export
          </button>
        </div>
        <div class="mode-switcher">
          <button
            class="mode-btn"
            [class.active]="mode === 'editing'"
            [disabled]="!document"
            (click)="setMode('editing')"
          >
            Edit
          </button>
          <button
            class="mode-btn"
            [class.active]="mode === 'suggesting'"
            [disabled]="!document"
            (click)="setMode('suggesting')"
          >
            Suggest
          </button>
          <button
            class="mode-btn"
            [class.active]="mode === 'viewing'"
            [disabled]="!document"
            (click)="setMode('viewing')"
          >
            View
          </button>
        </div>
      </header>
      <main class="editor-area">
        <div class="editor-wrapper">
          <div id="superdoc-toolbar" class="toolbar-container"></div>
          <div #editor class="editor-container"></div>
        </div>
      </main>
    </div>
  `,
  styles: [
    `
      .app {
        height: 100vh;
        display: flex;
        flex-direction: column;
        background: #f5f5f5;
      }

      .header {
        padding: 1rem 1.5rem;
        background: #1e2a3a;
        color: white;
        display: flex;
        align-items: center;
        justify-content: flex-end;
        gap: 1rem;
      }

      .header-actions {
        display: flex;
        align-items: center;
        gap: 0.75rem;
      }

      .btn {
        padding: 0.625rem 1.5rem;
        font-size: 0.9375rem;
        font-weight: 500;
        border-radius: 6px;
        cursor: pointer;
        transition: all 0.15s;
        min-width: 100px;
      }

      .btn.outlined {
        background: transparent;
        border: 1px solid rgba(255, 255, 255, 0.4);
        color: white;
      }

      .btn.outlined:hover {
        background: rgba(255, 255, 255, 0.1);
        border-color: rgba(255, 255, 255, 0.6);
      }

      .btn.filled {
        background: #2d3f52;
        border: 1px solid #3d5166;
        color: white;
      }

      .btn.filled:hover:not(:disabled) {
        background: #3d5166;
      }

      .btn:disabled {
        opacity: 0.5;
        cursor: not-allowed;
      }

      .mode-switcher {
        display: flex;
        align-items: center;
        gap: 0;
        margin-left: 0.5rem;
      }

      .mode-btn {
        padding: 0.5rem 1rem;
        font-size: 0.875rem;
        font-weight: 500;
        border: 1px solid rgba(255, 255, 255, 0.3);
        background: transparent;
        color: rgba(255, 255, 255, 0.8);
        cursor: pointer;
        transition: all 0.15s;
      }

      .mode-btn:first-child {
        border-radius: 6px 0 0 6px;
      }

      .mode-btn:last-child {
        border-radius: 0 6px 6px 0;
      }

      .mode-btn:not(:first-child) {
        border-left: none;
      }

      .mode-btn:hover:not(:disabled) {
        background: rgba(255, 255, 255, 0.1);
        color: white;
      }

      .mode-btn.active {
        background: white;
        color: #1e2a3a;
        border-color: white;
      }

      .mode-btn.active + .mode-btn {
        border-left: 1px solid rgba(255, 255, 255, 0.3);
      }

      .mode-btn:disabled {
        opacity: 0.5;
        cursor: not-allowed;
      }

      .editor-area {
        flex: 1;
        min-height: 0;
        overflow: hidden;
        background: #e8e8e8;
      }

      .editor-wrapper {
        height: 100%;
        display: flex;
        flex-direction: column;
      }

      .toolbar-container {
        flex-shrink: 0;
        border-bottom: 1px solid #e5e7eb;
        background: white;
      }

      .editor-container {
        flex: 1;
        min-height: 0;
        overflow: auto;
        background: #e8e8e8;
        padding-top: 1rem;
        padding-left: 1rem;
        padding-right: 1rem;
        display: flex;
        justify-content: center;
      }

      .editor-container > * {
        flex-shrink: 0;
      }
    `,
  ],
})
export class AppComponent implements OnDestroy {
  @ViewChild('editor', { static: true }) editorRef!: ElementRef;

  private superdoc: SuperDoc | null = null;
  private ydoc: Y.Doc | null = null;
  private provider: HocuspocusProvider | null = null;
  document: File | null = null;
  mode: 'editing' | 'suggesting' | 'viewing' = 'editing';
  isReady = false;

  constructor(private ngZone: NgZone) {}

  onFileChange(event: Event) {
    const file = (event.target as HTMLInputElement).files?.[0];
    if (!file) return;

    this.document = file;
    this.isReady = false;
    this.cleanup();

    // Create Y.js document and Hocuspocus provider for collaboration
    const documentId = `doc-${file.name}-${Date.now()}`;
    this.ydoc = new Y.Doc();
    this.provider = new HocuspocusProvider({
      url: 'ws://localhost:1234',
      name: documentId,
      document: this.ydoc,
    });

    this.superdoc = new SuperDoc({
      selector: this.editorRef.nativeElement,
      documentMode: this.mode,
      document: file,
      toolbar: '#superdoc-toolbar',
      rulers: true,
      user: {
        name: 'John Doe',
        email: 'john@example.com',
      },
      modules: {
        collaboration: {
          ydoc: this.ydoc,
          provider: this.provider,
        },
      },
      onReady: () => {
        this.ngZone.run(() => {
          this.isReady = true;
        });
      },
    });
  }

  private cleanup() {
    this.provider?.destroy();
    this.ydoc?.destroy();
    this.superdoc?.destroy();
    this.provider = null;
    this.ydoc = null;
    this.superdoc = null;
  }

  setMode(mode: 'editing' | 'suggesting' | 'viewing') {
    this.mode = mode;
    if (this.superdoc) {
      this.superdoc.setDocumentMode(mode);
    }
  }

  async exportDocument() {
    if (!this.superdoc || !this.document) {
      alert('Please import a document first');
      return;
    }
    await this.superdoc.export({ triggerDownload: true });
  }

  ngOnDestroy() {
    this.cleanup();
  }
}

// examples/features/search-demo/src/App.vue
<script setup>
import { ref, watch, onMounted } from 'vue';
import { SuperDoc } from 'superdoc';

// State
const file = ref(null);
const loading = ref(false);
const ready = ref(false);
const query = ref('');
const results = ref([]);
const activeResult = ref(null);
const replaceText = ref('');

// SuperDoc instance
let superdoc = null;

// Handle file selection
const onFileChange = (e) => {
  file.value = e.target.files?.[0] || null;
};

// Initialize SuperDoc
const initSuperdoc = (doc = null) => {
  superdoc?.destroy();
  results.value = [];
  query.value = '';
  loading.value = !!doc;
  ready.value = false;

  superdoc = new SuperDoc({
    selector: '#editor',
    document: doc,
    documentMode: 'editing',
    pagination: true,
    toolbar: 'toolbar',
    toolbarGroups: ['left', 'center', 'right'],
    trackChanges: {
      enabled: true,
      visible: true,
    },
    user: {
      name: 'Demo User',
      email: 'demo@example.com',
    },
    onReady: () => {
      loading.value = false;
      ready.value = true;
    },
  });
};

// Start with blank doc
onMounted(() => initSuperdoc());

// Reinitialize when file changes
watch(file, (newFile) => {
  if (newFile) initSuperdoc(newFile);
});

// ============================================
// SEARCH CODE
// ============================================

const search = () => {
  if (!superdoc || !query.value.trim()) {
    results.value = [];
    return;
  }

  // Search returns array of matches with { from, to, text }
  results.value = superdoc.search(query.value) ?? [];
};

const goToResult = (result) => {
  // Scrolls to the result and highlights it
  superdoc?.goToSearchResult(result);
  activeResult.value = result;
};

// ============================================
// REPLACE CODE
// ============================================

const replacing = ref(false);

const replace = async () => {
  if (!superdoc || !activeResult.value) return;

  const { from, to } = activeResult.value;
  const editor = superdoc.activeEditor;

  replacing.value = true;

  try {
    editor.commands.insertTrackedChange({
      from,
      to,
      text: replaceText.value,
    });
  } catch (err) {
    console.error('[replace] error:', err);
  }

  // Clear state and re-search
  activeResult.value = null;
  replaceText.value = '';
  replacing.value = false;
  search();
};

const truncate = (text, max = 40) => {
  const clean = text.replace(/\s+/g, ' ').trim();
  return clean.length > max ? clean.slice(0, max) + '...' : clean;
};
</script>

<template>
  <div class="app">
    <!-- Header -->
    <header class="header">
      <div class="header-left">
        <span class="badge">SEARCH DEMO</span>
      </div>
      <div class="header-right">
        <label class="file-btn">
          Choose File
          <input type="file" accept=".docx" @change="onFileChange" />
        </label>
        <span class="filename">{{ file?.name || 'No file chosen' }}</span>
      </div>
    </header>

    <!-- Toolbar -->
    <div id="toolbar"></div>

    <!-- Main -->
    <main class="main">
      <!-- Editor -->
      <div id="editor">
        <div v-if="loading" class="loading">Loading...</div>
      </div>

      <!-- Sidebar -->
      <aside class="sidebar">
        <div class="sidebar-header">Search</div>
        <div class="sidebar-body">
          <label class="label">Query</label>
          <div class="search-row">
            <input
              v-model="query"
              type="text"
              placeholder="Search..."
              :disabled="!ready"
              @keydown.enter="search"
            />
            <button :disabled="!ready" @click="search">Search</button>
          </div>

          <div class="results">
            <div v-if="results.length === 0" class="hint">No results</div>
            <button
              v-for="(r, i) in results"
              :key="i"
              class="result"
              :class="{ active: activeResult === r }"
              @click="goToResult(r)"
            >
              <span class="result-index">{{ i + 1 }}.</span>
              <span class="result-text">{{ truncate(r.text) }}</span>
            </button>
          </div>

          <!-- Replace section -->
          <div v-if="activeResult" class="replace-section">
            <label class="label">Replace with</label>
            <textarea
              v-model="replaceText"
              class="replace-input"
              placeholder="Enter replacement text..."
              rows="3"
            ></textarea>

            <button class="replace-btn" :disabled="replacing" @click="replace">
              {{ replacing ? 'Replacing...' : 'Replace as Tracked Change' }}
            </button>
          </div>
        </div>
      </aside>
    </main>
  </div>
</template>

<style scoped>
.app {
  display: flex;
  flex-direction: column;
  height: 100%;
}

/* Header */
.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 8px 16px;
  background: #1e293b;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 12px;
}

.badge {
  background: #334155;
  color: #94a3b8;
  font-size: 10px;
  font-weight: 600;
  padding: 4px 8px;
  border-radius: 4px;
}

.header-right {
  display: flex;
  align-items: center;
  gap: 10px;
}

.file-btn {
  background: #3b82f6;
  color: #fff;
  padding: 6px 12px;
  border-radius: 4px;
  font-size: 12px;
  font-weight: 500;
  cursor: pointer;
}

.file-btn:hover {
  background: #2563eb;
}

.file-btn input {
  display: none;
}

.filename {
  color: #cbd5e1;
  font-size: 12px;
}

/* Toolbar */
#toolbar {
  background: #fff;
  border-bottom: 1px solid #e2e8f0;
}

/* Main */
.main {
  display: flex;
  flex: 1;
  min-height: 0;
}

#editor {
  flex: 1;
  overflow: auto;
  background: #e2e8f0;
  position: relative;
}

.loading {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 16px;
  color: #64748b;
  background: #e2e8f0;
  z-index: 10;
}

/* Sidebar */
.sidebar {
  width: 260px;
  background: #fff;
  border-left: 1px solid #e2e8f0;
  display: flex;
  flex-direction: column;
}

.sidebar-header {
  padding: 12px 16px;
  font-size: 14px;
  font-weight: 600;
  border-bottom: 1px solid #e2e8f0;
}

.sidebar-body {
  padding: 12px;
  display: flex;
  flex-direction: column;
  gap: 8px;
  overflow-y: auto;
}

.label {
  font-size: 11px;
  font-weight: 600;
  color: #64748b;
  text-transform: uppercase;
}

.search-row {
  display: flex;
  gap: 6px;
}

.search-row input {
  flex: 1;
  padding: 6px 10px;
  border: 1px solid #cbd5e1;
  border-radius: 6px;
  font-size: 13px;
}

.search-row button {
  padding: 6px 12px;
  background: #3b82f6;
  color: #fff;
  border: none;
  border-radius: 6px;
  font-size: 12px;
  font-weight: 600;
  cursor: pointer;
}

.search-row button:disabled {
  background: #94a3b8;
}

.results {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.hint {
  color: #94a3b8;
  font-size: 12px;
  padding: 8px 0;
}

.result {
  display: flex;
  align-items: baseline;
  gap: 6px;
  padding: 8px 10px;
  background: #fff;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  text-align: left;
  cursor: pointer;
  font-size: 12px;
}

.result:hover {
  border-color: #3b82f6;
  background: #f8fafc;
}

.result.active {
  border-color: #3b82f6;
  background: #eff6ff;
}

.result-index {
  font-weight: 600;
  color: #3b82f6;
}

.result-text {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* Replace section */
.replace-section {
  display: flex;
  flex-direction: column;
  gap: 8px;
  margin-top: 12px;
  padding-top: 12px;
  border-top: 1px solid #e2e8f0;
}

.replace-input {
  padding: 8px 10px;
  border: 1px solid #cbd5e1;
  border-radius: 6px;
  font-size: 13px;
  font-family: inherit;
  resize: vertical;
}

.replace-input:focus {
  outline: none;
  border-color: #3b82f6;
}

.replace-btn {
  padding: 8px 12px;
  background: #3b82f6;
  color: #fff;
  border: none;
  border-radius: 6px;
  font-size: 12px;
  font-weight: 600;
  cursor: pointer;
}

.replace-btn:hover {
  background: #2563eb;
}

.replace-btn:disabled {
  background: #94a3b8;
  cursor: not-allowed;
}
</style>
