// examples/advanced/build-your-own-ui/src/components/CommentComposer.tsx
import { useEffect, useRef, useState } from 'react';
import { shallowEqual } from 'superdoc/ui';
import { useSuperDocUI, useSuperDocSlice } from '../lib/SuperDocUIProvider';

interface Props {
  /** Close the composer without posting. */
  onCancel(): void;
  /** Called after a successful create so the parent can dismiss / scroll. */
  onPosted(commentId: string | null): void;
}

/**
 * Inline composer for new comments. Mounts inside the activity panel
 * when the toolbar's comment button is clicked. Captures the current
 * selection target on submit and routes through
 * `ui.comments.createFromSelection({ text })`.
 *
 * Why an inline composer instead of `window.prompt`: a real product UI
 * doesn't pop a browser dialog. The composer also lets the user
 * preview the quoted text — the snippet that will be anchored — so
 * they know what they're commenting on.
 */
export function CommentComposer({ onCancel, onPosted }: Props) {
  const ui = useSuperDocUI();
  const [text, setText] = useState('');
  const [posting, setPosting] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement | null>(null);

  const selection = useSuperDocSlice(
    (controller) => controller.select((state) => state.selection, shallowEqual),
    {
      empty: true,
      target: null as null | unknown,
      activeMarks: [] as string[],
      activeCommentIds: [] as string[],
      activeChangeIds: [] as string[],
      quotedText: '',
    } as never,
  );

  // Autofocus the textarea on mount — the consumer-flow expectation is
  // "click comment icon, start typing immediately."
  useEffect(() => {
    textareaRef.current?.focus();
  }, []);

  const canPost = !!ui && !!selection.target && !posting && text.trim().length > 0;

  const post = () => {
    if (!ui || !canPost) return;
    setPosting(true);
    try {
      const receipt = ui.comments.createFromSelection({ text: text.trim() });
      setPosting(false);
      if (!receipt.success) {
        onPosted(null);
        return;
      }
      const entity = receipt.inserted?.[0];
      onPosted((entity as { entityId?: string } | undefined)?.entityId ?? null);
    } catch (err) {
      console.error('[CommentComposer] createFromSelection threw', err);
      setPosting(false);
    }
  };

  return (
    <div className="composer">
      <div className="composer-quote">
        {selection.quotedText ? <>“{selection.quotedText}”</> : <em>No selection</em>}
      </div>
      <textarea
        ref={textareaRef}
        className="composer-input"
        rows={3}
        placeholder="Write a comment…"
        value={text}
        onChange={(e) => setText(e.target.value)}
        onKeyDown={(e) => {
          if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') post();
          if (e.key === 'Escape') onCancel();
        }}
      />
      <div className="composer-actions">
        <button onClick={onCancel}>Cancel</button>
        <button className="primary" disabled={!canPost} onClick={post}>
          {posting ? 'Posting…' : 'Comment'}
        </button>
      </div>
    </div>
  );
}

// demos/editor/layout-change/src/CommentComposer.vue
<script setup lang="ts">
import { ref, onMounted, inject, computed } from 'vue';
import type { SuperDocUI, SelectionCapture } from 'superdoc/ui';

const emit = defineEmits<{
  cancel: [];
  posted: [commentId: string | null];
}>();

// Inject the UI controller from parent
const ui = inject<{ value: SuperDocUI | null }>('superdoc-ui');

const text = ref('');
const posting = ref(false);
const textareaRef = ref<HTMLTextAreaElement | null>(null);

// Capture selection at mount time - must happen before textarea takes focus
let captured: SelectionCapture | null = null;
onMounted(() => {
  if (ui?.value) {
    captured = ui.value.selection.capture();
  }
  textareaRef.value?.focus();
});

const quotedText = computed(() => captured?.quotedText ?? null);
const canPost = computed(() => !!ui?.value && !!captured && !posting.value && text.value.trim().length > 0);

function post() {
  if (!ui?.value || !canPost.value || !captured) return;
  posting.value = true;
  try {
    const receipt = ui.value.comments.createFromCapture(captured, { text: text.value.trim() });
    posting.value = false;
    if (!receipt.success) {
      emit('posted', null);
      return;
    }
    // Restore selection
    ui.value.selection.restore(captured);
    const entity = (receipt.inserted as Array<{ entityId?: string }> | undefined)?.[0];
    emit('posted', entity?.entityId ?? null);
  } catch (err) {
    console.error('[CommentComposer] createFromCapture threw', err);
    posting.value = false;
  }
}

function cancel() {
  // Restore selection on cancel too
  if (ui?.value && captured) {
    ui.value.selection.restore(captured);
  }
  emit('cancel');
}

function handleKeydown(e: KeyboardEvent) {
  if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') post();
  if (e.key === 'Escape') cancel();
}
</script>

<template>
  <div class="composer">
    <div class="composer-quote">
      <template v-if="quotedText">"{{ quotedText }}"</template>
      <em v-else>No selection</em>
    </div>
    <textarea
      ref="textareaRef"
      class="composer-input"
      rows="3"
      placeholder="Write a comment…"
      v-model="text"
      @keydown="handleKeydown"
    />
    <div class="composer-actions">
      <button @click="cancel">Cancel</button>
      <button class="primary" :disabled="!canPost" @click="post">
        {{ posting ? 'Posting…' : 'Comment' }}
      </button>
    </div>
  </div>
</template>
